#!/usr/bin/perl

# Begin-Doc
# Name: fixperms
# Description: helper script to run handle-fixperms via sudo if necessary
# End-Doc

use strict;
use Cwd;
use Getopt::Long;

my $user = $ENV{SUDO_USER};
if ( $user eq "" ) {
    exec( "/usr/bin/sudo", "/usr/bin/fixperms", @ARGV );
}

if ( $user eq "root" ) {
    my $cwd = getcwd;
    if ( $cwd =~ m|^/local/([^/]+)| ) {
        if ( getpwnam($1) ) {
            $user = $1;
            print "Running as root, forcing user to $user based on current dir ($cwd).\n";
        }
    }
}
if ( $user eq "root" ) {
    die "Cannot run fixperms for root.\n";
}

my $ignore_user;
my $ignore_dir;
my $help;

Getopt::Long::Configure("pass_through");
my $res = GetOptions( "user=s" => \$ignore_user, "dir=s" => \$ignore_dir, "help+" => \$help );

if ( $ignore_user || $ignore_dir ) {
    print "Cannot specify user or dir when calling $0 helper.\n";
    exit(1);
}

my @info = getpwnam($user);
if ( $user ne $info[0] ) {
    die "Cannot determine user to run as!\n" if ( !$user );
}

my @args = ();
push( @args, "--user" => $user );
push( @args, "--dir"  => $info[7] );
if ($help) {
    push( @args, "--help" );
}

system( "/usr/sbin/handle-fixperms", @args, @ARGV );
